<?php
/**
 * @file
 * moo_team.features.user_permission.inc
 */

/**
 * Implements hook_user_default_permissions().
 */
function moo_team_user_default_permissions() {
  $permissions = array();

  // Exported permission: create team content.
  $permissions['create team content'] = array(
    'name' => 'create team content',
    'roles' => array(
      'developer' => 'developer',
      'team' => 'team',
    ),
    'module' => 'node',
  );

  // Exported permission: delete any team content.
  $permissions['delete any team content'] = array(
    'name' => 'delete any team content',
    'roles' => array(
      'developer' => 'developer',
      'team' => 'team',
    ),
    'module' => 'node',
  );

  // Exported permission: delete own team content.
  $permissions['delete own team content'] = array(
    'name' => 'delete own team content',
    'roles' => array(
      'developer' => 'developer',
      'team' => 'team',
    ),
    'module' => 'node',
  );

  // Exported permission: edit any team content.
  $permissions['edit any team content'] = array(
    'name' => 'edit any team content',
    'roles' => array(
      'developer' => 'developer',
      'team' => 'team',
    ),
    'module' => 'node',
  );

  // Exported permission: edit own team content.
  $permissions['edit own team content'] = array(
    'name' => 'edit own team content',
    'roles' => array(
      'developer' => 'developer',
      'team' => 'team',
    ),
    'module' => 'node',
  );

  return $permissions;
}
